### PR TITLE
Use remote theme

### PR DESCRIPTION
**Pull request by fmichonneau**
addresses #29 

This pull request brings in the remote theme for this lesson.

### CODE REVIEW

**Comment by alex-konovalov** [comment]
Thank you @fmichonneau ! I've checked out the PR and did the following:
```
$ make serve
bundle exec jekyll serve
Configuration file: /Users/alexk/GITREPS/SWC_DC/gap-lesson/_config.yml
            Source: /Users/alexk/GITREPS/SWC_DC/gap-lesson
       Destination: /Users/alexk/GITREPS/SWC_DC/gap-lesson/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Invalid theme folder: _sass
      Remote Theme: Using theme carpentries/carpentries-theme
Invalid theme folder: _sass
                    done in 2.399 seconds.
 Auto-regeneration: enabled for '/Users/alexk/GITREPS/SWC_DC/gap-lesson'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```
Except the message about `_sass` folder, the result looks OK to me.

**Comment by alex-konovalov** [comment]
Also while navigating, the following messages printed in the terminal:
```
[2019-10-23 20:15:15] ERROR `/edit/setup.md' not found.
[2019-10-23 20:15:15] ERROR `/favicon.ico' not found.
```

**Comment by ErinBecker** [comment]
Thanks for testing @alex-konovalov. It sounds like things generally worked, so I'm going to go ahead and merge this PR so we can start communicating about the Incubator lessons more broadly with the community. I'll leave this PR open so that @fmichonneau can address those navigation errors if needed.

**Comment by alex-konovalov** [comment]
Thanks @ErinBecker - the content looks OK, and I am not familiar with the new theme to decide if all works as intended or not. The Carpentries Incubator logo is not there, so perhaps some more tweaks will be needed, but hopefully it will stabilise shortly.

**Pull request merged**
